/**
 * Protocol Corpus — static loader
 * -------------------------------
 * Loads the OCR extraction of all Australian pharmacist prescribing /
 * expanded-scope protocols (113 JSON files, 8 jurisdictions, as at
 * Sep 2026) bundled under `src/data/protocol-corpus/protocols/`.
 *
 * The corpus is IMMUTABLE reference data: every document carries its own
 * instrument version, effective date, legal basis, per-item provenance
 * (pdf sha256 + page + section heading) and extraction confidence.
 * Clinical logic in consultations reads from here but NEVER auto-writes:
 * the pharmacist makes and records every decision.
 *
 * Files and their classification come from manifest.json (generated by
 * scripts/build_manifest.py from the source zip). Raw payloads are
 * imported eagerly (≈2.5 MB) — this is a local-first app.
 */
import manifest from './manifest.json';
import type {
  CorpusConditionGroup,
  CorpusDocumentMeta,
  CorpusManifest,
  CorpusProvenance,
  CorpusRedFlag,
  CorpusTreatment,
  CorpusCriteriaItem,
  CorpusDocumentPayload,
} from './types';


const m = manifest as unknown as CorpusManifest;

/** Raw JSON payloads, keyed by file name. */
const payloads: Record<string, CorpusDocumentPayload> = {};
const rawModules = import.meta.glob('./protocols/*.json', { eager: true });
for (const [path, mod] of Object.entries(rawModules)) {
  const file = path.split('/').pop();
  if (!file) continue;
  payloads[file] = (mod as { default: CorpusDocumentPayload }).default;
}

export const CORPUS_AS_AT = m.asAt;
export const CORPUS_SCHEMA_VERSION = m.schemaVersion;
export const CORPUS_STATES = m.states;

/** Manifest-level document metadata (classification, counts, hashes). */
export const CORPUS_DOCUMENTS: CorpusDocumentMeta[] = m.documents;

/** Condition groups: conditionKey → { label, registrySlug, states, docs }. */
export const CORPUS_CONDITIONS: CorpusConditionGroup[] = Object.values(m.conditions);

const BY_KEY = new Map<string, CorpusConditionGroup>(CORPUS_CONDITIONS.map(c => [c.key, c]));

export function getConditionGroup(key: string): CorpusConditionGroup | undefined {
  return BY_KEY.get(key);
}

/** All corpus documents whose condition maps to a consultation registry slug. */
export function getConditionDocsForSlug(registrySlug: string): CorpusDocumentMeta[] {
  return CORPUS_DOCUMENTS.filter(d => d.registrySlug === registrySlug);
}

/** Jurisdictions that authorise a registry condition, with doc counts. */
export function getJurisdictionsForSlug(registrySlug: string): { state: string; docs: CorpusDocumentMeta[] }[] {
  const out = new Map<string, CorpusDocumentMeta[]>();
  for (const d of CORPUS_DOCUMENTS) {
    if (d.registrySlug !== registrySlug || d.docType === 'repealed') continue;
    const list = out.get(d.state) ?? [];
    list.push(d);
    out.set(d.state, list);
  }
  return Array.from(out.entries())
    .map(([state, docs]) => ({ state, docs }))
    .sort((a, b) => a.state.localeCompare(b.state));
}

export function getDocsForConditionKey(conditionKey: string): CorpusDocumentMeta[] {
  return CORPUS_DOCUMENTS.filter(d => d.conditionKey === conditionKey);
}

export function getDocsForState(state: string): CorpusDocumentMeta[] {
  return CORPUS_DOCUMENTS.filter(d => d.state === state);
}

/** Full payload for one corpus document (null when not bundled). */
export function getPayload(file: string): CorpusDocumentPayload | null {
  return payloads[file] ?? null;
}

/** Case-insensitive search across instrument names, legal basis and scope summaries. */
export function searchCorpus(query: string): CorpusDocumentMeta[] {
  const q = query.trim().toLowerCase();
  if (!q) return CORPUS_DOCUMENTS;
  return CORPUS_DOCUMENTS.filter(d =>
    (d.title || '').toLowerCase().includes(q) ||
    (d.legalBasis || '').toLowerCase().includes(q) ||
    (d.scopeSummary || '').toLowerCase().includes(q) ||
    d.conditionLabel.toLowerCase().includes(q) ||
    d.state.toLowerCase().includes(q)
  );
}

export function formatProvenance(p?: CorpusProvenance): string {
  if (!p) return '';
  const page = p.page ? ` p. ${p.page}` : '';
  const heading = p.section_heading ? ` — ${p.section_heading}` : '';
  return `${p.pdf_file}${page}${heading}`;
}

export function shortSha(sha?: string | null): string {
  return sha ? sha.slice(0, 12) : '—';
}

/** Human severity label for red flags. */
export function severityTone(sev?: string): 'critical' | 'high' | 'moderate' | 'low' {
  switch ((sev || '').toLowerCase()) {
    case 'critical': return 'critical';
    case 'high': return 'high';
    case 'medium': return 'moderate';
    case 'low': return 'low';
    default: return 'moderate';
  }
}

/**
 * Evaluate a structured red-flag rule against live consultation data.
 * Currently supports `age` (derived from DOB). Numeric vitals keys are
 * supported when the form captures them (`temperature`, `heart_rate`,
 * `systolic_bp`). Returns 'unverifiable' when the form has no value —
 * the rule is then surfaced as a checklist item for the pharmacist.
 */
export function evaluateStructuredRule(
  rule: NonNullable<CorpusRedFlag['structured']>,
  formData: Record<string, unknown> | undefined,
): 'pass' | 'fail' | 'unverifiable' {
  if (!formData) return 'unverifiable';
  const param = rule.parameter.toLowerCase();
  let value: number | undefined;
  if (param === 'age') {
    const dob = formData.dob as string | undefined;
    if (!dob) return 'unverifiable';
    const d = new Date(dob);
    if (isNaN(d.getTime())) return 'unverifiable';
    const now = new Date();
    value = now.getFullYear() - d.getFullYear();
    const m = now.getMonth() - d.getMonth();
    if (m < 0 || (m === 0 && now.getDate() < d.getDate())) value -= 1;
  } else {
    const candidates = [param, param.replace(/_/g, ''), `vitals.${param}`];
    for (const key of candidates) {
      const raw = formData[key];
      if (raw !== undefined && raw !== null && String(raw).trim() !== '') {
        const n = parseFloat(String(raw));
        if (!isNaN(n)) { value = n; break; }
      }
    }
    if (value === undefined) return 'unverifiable';
  }
  const target = typeof rule.value === 'number' ? rule.value : parseFloat(rule.value);
  if (isNaN(target)) return 'unverifiable';
  switch (rule.operator) {
    case '<': return value < target ? 'fail' : 'pass';
    case '<=': return value <= target ? 'fail' : 'pass';
    case '>': return value > target ? 'fail' : 'pass';
    case '>=': return value >= target ? 'fail' : 'pass';
    case '==': case '=': return value === target ? 'fail' : 'pass';
    case '!=': return value !== target ? 'fail' : 'pass';
    default: return 'unverifiable';
  }
}

/** Jurisdiction-availability helper for the registry (pure, hook-free). */
export function corpusJurisdictionsForSlug(registrySlug: string): string[] {
  return getJurisdictionsForSlug(registrySlug).map(j => j.state);
}

export type {
  CorpusProvenance,
  CorpusStructuredRule,
  CorpusRedFlag,
  CorpusTreatment,
  CorpusCriteriaItem,
  CorpusPathway,
  CorpusPathwayStep,
  CorpusDocumentPayload,
  CorpusDocumentMeta,
  CorpusConditionGroup,
  CorpusManifest,
} from './types';